version: "3.8"

services:
  vmA:
    image: ethereum/client-go:stable
    container_name: vmA
    volumes:
      - ./vmA/gethdata:/root/.ethereum
      - ./genesis.json:/genesis.json
    command: >
      sh -c "
        geth init /genesis.json &&
        geth --networkid 2025 --http --http.addr 0.0.0.0 --http.port 8545
             --http.api personal,eth,net,web3,miner
             --mine --miner.threads=1 --nodiscover --verbosity 3
      "
    ports:
      - "8545:8545"
      - "30303:30303"

  vmB:
    image: ethereum/client-go:stable
    container_name: vmB
    volumes:
      - ./vmB/gethdata:/root/.ethereum
      - ./genesis.json:/genesis.json
    command: >
      sh -c "
        geth init /genesis.json &&
        geth --networkid 2025 --http --http.addr 0.0.0.0 --http.port 8546
             --http.api personal,eth,net,web3,miner
             --mine --miner.threads=1 --nodiscover --verbosity 3
             --bootnodes enode://BOOTNODE_KEY@vmA:30303
      "
    ports:
      - "8546:8546"
      - "30304:30303"
